// #![deny(clippy::disallowed_method)]
// #![deny(clippy::all)]
// #![deny(clippy::perf)]
// #![deny(clippy::style)]
// #![deny(clippy::cargo)]
// #![deny(clippy::correctness)]
// #![deny(clippy::suspicious)]
// #![deny(clippy::complexity)]
// #![warn(clippy::needless_return)]
// #![warn(clippy::nursery)]
// #![warn(clippy::pedantic)]
// #![allow(clippy::too_many_lines)]
// #![allow(clippy::non_ascii_literal)]
// #![allow(clippy::single_match_else)]
// #![allow(clippy::let_underscore_drop)]
// #![allow(clippy::multiple_crate_versions)]
// #![feature(custom_inner_attributes)]
// #![clippy::msrv = "1.61.0"]

pub mod schemas;
pub mod utils;
